<?= $this->extend('admin/_layout_/layout') ?>
<?= $this->section('content') ?>
<?php
$labels = ['awaiting_payment'=>'در انتظار پرداخت','payment_pending'=>'در حال پرداخت','paid'=>'پرداخت‌شده','paid_stock_issue'=>'نیازمند بررسی موجودی','confirmed'=>'تأییدشده','expired'=>'منقضی','cancelled'=>'لغوشده'];
?>
<section class="py-5"><div class="container"><div class="grid my-4 grid-cols-1 lg:grid-cols-4 gap-8">
<?= $this->include('admin/_layout_/layout_sidebar') ?>
<div class="lg:col-span-3 space-y-7">
    <div class="bg-white rounded-2xl drop-shadow-lg p-6 dark:bg-custom-dark dark:border dark:border-gray-700">
        <div class="flex flex-wrap justify-between items-center gap-4"><div><h1 class="font-black text-2xl with-highlight dark:text-gray-200">سفارش #<?= (int)$order['id'] ?></h1><p class="text-gray-500 mt-2"><?= esc($order['customer_firstname'].' '.$order['customer_lastname']) ?> — <?= esc($order['customer_mobile']) ?></p></div><a href="<?= site_url(ADMIN_PATH.'/order') ?>" class="bg-primary text-white py-2.5 px-4 rounded-lg">بازگشت به سفارش‌ها</a></div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mt-6 text-sm"><div class="bg-gray-50 dark:bg-gray-800 rounded-xl p-4"><span class="text-gray-500">وضعیت</span><strong class="block mt-2"><?= $labels[$order['status']] ?? esc($order['status']) ?></strong></div><div class="bg-gray-50 dark:bg-gray-800 rounded-xl p-4"><span class="text-gray-500">جمع محصولات</span><strong class="block mt-2"><?= number_format($order['subtotal']) ?> تومان</strong></div><div class="bg-gray-50 dark:bg-gray-800 rounded-xl p-4"><span class="text-gray-500">مبلغ نهایی</span><strong class="block mt-2"><?= number_format($order['total']) ?> تومان</strong></div></div>
        <div class="mt-5 p-4 border border-gray-200 dark:border-gray-700 rounded-xl text-sm leading-7"><strong><?= esc($order['recipient_name'] ?? '') ?> — <?= esc($order['recipient_mobile'] ?? '') ?></strong><p><?= esc(($order['state_name'] ?? '').'، '.($order['city_name'] ?? '').'، '.($order['address_full'] ?? '')) ?></p><p>روش ارسال: <?= esc($order['shipping_type_name'] ?? '-') ?> — <?= number_format($order['shipping_price']) ?> تومان</p></div>
        <?php if ($order['status'] === 'paid'): ?><form method="post" action="<?= site_url(ADMIN_PATH.'/order/'.$order['id'].'/confirm') ?>" class="mt-5"><?= csrf_field() ?><button class="bg-green-600 hover:bg-green-700 text-white py-2.5 px-6 rounded-lg">تأیید سفارش پرداخت‌شده</button></form><?php endif; ?>
    </div>
    <div class="bg-white rounded-2xl drop-shadow-lg p-6 dark:bg-custom-dark dark:border dark:border-gray-700"><h2 class="font-black text-xl with-highlight mb-5">اقلام سفارش</h2><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr><th class="p-3 text-right">محصول</th><th class="p-3">تعداد</th><th class="p-3">قیمت واحد</th><th class="p-3">جمع</th></tr></thead><tbody><?php foreach($items as $item): ?><tr class="border-t"><td class="p-3"><?= esc($item['product_name']) ?></td><td class="p-3 text-center"><?= (int)$item['quantity'] ?></td><td class="p-3 text-center"><?= number_format(($item['sale_price'] > 0 && $item['sale_price'] < $item['price']) ? $item['sale_price'] : $item['price']) ?></td><td class="p-3 text-center font-bold"><?= number_format($item['total']) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
    <div class="bg-white rounded-2xl drop-shadow-lg p-6 dark:bg-custom-dark dark:border dark:border-gray-700"><h2 class="font-black text-xl with-highlight mb-5">تلاش‌های پرداخت</h2><div class="space-y-3"><?php foreach($payments as $payment): ?><div class="border border-gray-200 dark:border-gray-700 rounded-xl p-4 text-sm flex flex-wrap justify-between gap-3"><span>#<?= (int)$payment['id'] ?> — <?= esc($payment['status']) ?></span><span><?= number_format($payment['final_amount']) ?> تومان</span><span dir="ltr"><?= esc($payment['ref_number'] ?: $payment['gateway_track_id'] ?: '-') ?></span></div><?php endforeach; ?><?php if(!$payments): ?><p class="text-gray-500">هنوز تلاشی برای پرداخت ثبت نشده است.</p><?php endif; ?></div></div>
</div></div></div></section>
<?= $this->endSection() ?>
